name = "melanoma_prediction"
version = "0.1.0"
authors = ["Luca", "Enrique"]

[[programs]]
path = "src/main.py"
prime_size = 128

[[programs]]
path = "src/secret_addition.py"
name = "secret_addition"
prime_size = 128